version: '3'
services:
    fastapi-docker-example:
        image: fastapi-docker-example:latest
        container_name: fastapi-docker-example
        ports:
            - 8080:8080
        command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8080